Execute backup Command with run
backupshq/agent pull request #4
Opened 2019-09-06 14:15 UTC by DataSnaek

The `run` command on the agent will now execute what is in the `command` field of the Backup passed in. `ExecuteCommand()` seemed like a good candidate for moving to a utils file so I've put it in there.

My Go plugin has also reformatted all of the imports for the files I've edited. Is it ok to keep them like this or do you want me to disable the extension's auto-format option?

2019-09-09 09:27 UTC, glynnforrest requested changes
Looks good overall and works well. Just a little change to make r.e. returning a string in an error condition.

> Is it ok to keep them like this or do you want me to disable the extension's auto-format option?

That's fine, I should setup a lint check in a CI build. Go only has "1 way to do it" r.e. auto-formatting, and your editor is doing it correctly.

2019-09-09 09:27 UTC, glynnforrest commented on utils/utils.go
> +func ExecuteCommand(cmd string) string {
Let's return `(string, error)` here. We shouldn't only return a `string` in an error condition, and I'd also want to see why `cmd` failed. This function will just eat that error instead.

A somewhat unavoidable pattern in Go is the `_, err := func(); if err != nil {}` pattern. I think it only makes sense to check for an error when calling `utils.ExecuteCommand()` as well. I still see utility in this helper function though, and it'll no doubt expand as we run more complex commands in the future.

2019-09-09 09:27 UTC, glynnforrest commented on utils/utils.go
> +		return "Error executing command"
`return nil, errors.New("Error executing command: " + err.Error())`

2019-09-09 09:27 UTC, glynnforrest commented on utils/utils.go
> +	return string(out)
`return string(out), nil`

2019-09-10 11:44 UTC, DataSnaek commented
@glynnforrest Ok I've made those requested changes. I ended up returning an empty string instead of nil, if I wanted to return nil then I think I have to change the command output around to use pointers instead which seems unnecessary for now anyway.

I've also committed my changes for sending command output logs off to the API to this branch since the changes are quite closely related.

2019-09-10 17:53 UTC, glynnforrest approved these changes

2019-09-10 17:53 UTC, merged

2019-09-10 17:55 UTC, glynnforrest commented
>  if I wanted to return nil then I think I have to change the command output around to use pointers instead which seems unnecessary for now anyway.

Good catch, yup that's absolutely grand!

> I've also committed my changes for sending command output logs off to the API to this branch since the changes are quite closely related.

I haven't reviewed those changes so removed them from this PR. I've rebased and put them on a separate branch: https://github.com/backupshq/agent/tree/send-logs