Job scheduling
backupshq/agent pull request #6
Opened 2019-09-20 14:59 UTC by DataSnaek

Here's an initial PR for [T19](https://projects.backbeat.tech/projects/1031eb11-10e9-11e8-a781-f23c916e1390/tasks/19)

I decided to go with this cron package: https://godoc.org/github.com/robfig/cron

It handles expressions _and_ scheduling them. Is that what we want? In the task discussion you mentioned that the agent could check every x minutes and decide which backups it should run which is more manual, but this package will handle all of that for us.

For now the main loop runs every minute, and it will randomly assign each backup it pulls a cron expression for run every 1-2 minutes.

2019-09-24 17:21 UTC, glynnforrest requested changes
Really great work here! I like how you're scheduling the backups. Nice find with the cron package too.

A few changes please:

* More logging (no such thing as too much, check out what consul or the salt-minion dump to their logs)
* Run the backup check immediately on startup as well as every minute
* Cron package in Makefile


We're at the point now where passing a base `*http.Client` and `tokenResponse` around is a bit repetitive, we should probably create an `ApiClient` struct with methods on it. Let's cover that in a pairing session together 👍

2019-09-24 17:21 UTC, glynnforrest commented on command/agent.go
> +	"github.com/robfig/cron"
Can you update the `Makefile` to make sure this dependency is included?

2019-09-24 17:21 UTC, glynnforrest commented on command/agent.go
Here would be a good spot for some more logging. Seeing "Checking for changes to backups..." in the output with no other lines could disconcerting. I'd like to see the number of backups fetched, even if none were found or none of them are scheduled. Even a debug log line showing "Found 5 backups, all are already scheduled" would be very useful.

2019-09-24 17:21 UTC, glynnforrest commented on command/agent.go
> +		crons := map[string]*cron.Cron{}
This is an elegant solution, very nice!

2019-09-24 17:21 UTC, glynnforrest commented on command/agent.go
> +		cr.AddFunc("* * * * *", func() {
Can we run this function immediately when the agent starts, as well as every minute? I'd probably extract the anonymous function to a named function, then call it.

```go
check() // pick a better name than me
cr.AddFunc("* * * * *", check)
```

2019-09-24 17:21 UTC, glynnforrest commented on utils/scheduler.go
> +func Schedule(client *http.Client, tokenResponse auth.AccessTokenResponse, backup actions.Backup) *cron.Cron {
You've probably noticed a pattern emerging here, we'll refactor to use an ApiClient struct instead. Then we'd pass it into this function: `Schedule(apiClient, backup)`

2019-09-25 20:39 UTC, DataSnaek commented
@glynnforrest That's all of those changes pushed. Is that a suitable amount of logging for the main loop?

Other changes: 
* Updated to use cron expressions from the API as per your branch.
* The sync frequency (not sure about that terminology, what do you think?) can now be specified as a CLI argument.

2019-09-26 09:18 UTC, glynnforrest approved these changes

2019-09-26 09:18 UTC, merged